---
# File: tasks/CentOS.yml - CentOS tasks for nomad

- name: "Distribution specific variables"
  include_vars: "{{ ansible_distribution }}.yml"

- name: OS Packages
  yum: "name={{ item }} state=present"
  with_items: nomad_centos_os_packages
  tags: installation

- name: Download nomad
  get_url: "url={{ nomad_zip_url }} dest=/tmp/{{ nomad_centos_pkg }} sha256sum={{ nomad_centos_sha256 }} timeout=74"
  tags: installation

- name: Install nomad
  unarchive: "copy=no src=/tmp/{{ nomad_centos_pkg }} dest=/usr/local/bin/ owner={{ nomad_user }} group={{ nomad_group }} mode=0755"
  tags: installation

- name: Cleanup
  file:  path="/tmp/{{ nomad_centos_pkg }}" state=absent
  tags: installation
