---
# File: tasks/main.yml - Main tasks for nomad

- name: Fail if not a new release of Ubuntu
  fail:
    msg: "{{ ansible_distribution_version }} is not an acceptable version of Ubuntu for this role"
  when: ansible_lsb.id|lower == "ubuntu" and ( ansible_distribution_version|version_compare(12.04, '<') or ansible_distribution_version|version_compare(12.10, '=') )

- name: Fail if not a new release of Debian
  fail:
    msg: "{{ ansible_distribution_version }} is not an acceptable version of Debian for this role"
  when: ansible_lsb.id|lower == "debian" and ansible_distribution_version|version_compare(8.5, '<')

- name: Create cluster groupings
  group_by: key={{ nomad_node_role }}

- group_by: key=os_{{ ansible_os_family }}

- name: "Add nomad user"
  user: name=nomad comment="nomad user" uid=1047 group=bin

- name: "Add nomad user to docker group"
  user: name=nomad groups=docker append=yes
  when: nomad_enable_docker == "true"

- name: "CentOS tasks"
  include: CentOS.yml
  when: ansible_distribution  == "CentOS"

- name: "Debian tasks"
  include: Debian.yml
  when: ansible_distribution  == "Debian"

- name: "Red Hat tasks"
  include: RedHat.yml
  when: ansible_distribution  == "RedHat"

- name: "Ubuntu tasks"
  include: Ubuntu.yml
  when: ansible_distribution  == "Ubuntu"

- name: nomad directories
  file: "dest={{ item }} state=directory owner={{ nomad_user }} group={{ nomad_group}}"
  with_items:
    - /opt/nomad
    - /var/nomad
    - /var/run/nomad
    - /etc/nomad.d
    - /etc/nomad.d/bootstrap
    - /etc/nomad.d/server
    - /etc/nomad.d/client

- name: Initial nomad bootstrap configuration
  template: src=server_bootstrap.hcl.j2 dest={{ nomad_config_path }}/bootstrap/server_bootstrap.hcl

- name: Initial nomad server configuration
  template: src=server.hcl.j2 dest={{ nomad_config_path }}/server/server.hcl

- name: Initial nomad client configuration
  template: src=client.hcl.j2 dest={{ nomad_config_path }}/client/client.hcl

- name: SYSV init script
  template: src=nomad_sysvinit.j2 dest=/etc/init.d/nomad owner=root group=root mode=755
  when: not ansible_distribution == "Debian"

- name: Debian init script
  template: src=nomad_debian.init.j2 dest=/etc/init.d/nomad owner=root group=root mode=755
  when: ansible_distribution == "Debian" and ansible_distribution_major_version|int <= 7

- name: systemd script
  template: src=nomad_systemd.service.j2 dest=/lib/systemd/system/nomad.service owner=root group=root mode=644
  when: ansible_distribution_major_version|int >= 7

- name: Start nomad
  service: name=nomad state=started
