---
# File: tasks/Red Hat.yml - Red Hat tasks for nomad

- name: "Distribution specific variables"
  include_vars: "{{ ansible_distribution }}.yml"

# Download and install SELinux Python module (required by Ansible)  

- name: OS Packages
  yum: "name={{ item }} state=present"
  with_items: nomad_redhat_os_packages
  tags: installation

- name: Download nomad
  get_url: "url={{ nomad_zip_url }} dest=/tmp/{{ nomad_redhat_pkg }} sha256sum={{ nomad_redhat_sha256 }} timeout=74"
  tags: installation

- name: Install nomad
  unarchive: "copy=no src=/tmp/{{ nomad_redhat_pkg }} dest=/usr/local/bin/ owner={{ nomad_user }} group={{ nomad_group }} mode=0755"
  tags: installation

- name: Cleanup
  sudo: True
  shell: "rm -rf /tmp/{{ nomad_redhat_pkg }}"
  tags: installation
